language: python
env:
  - TOX_ENV=docs
  - TOX_ENV=py26-1.4
  - TOX_ENV=py26-1.5
  - TOX_ENV=py26-1.6
  - TOX_ENV=py27-1.4
  - TOX_ENV=py27-1.5
  - TOX_ENV=py27-1.6
  - TOX_ENV=py27-master
  - TOX_ENV=py33-1.5
  - TOX_ENV=py33-1.6
  - TOX_ENV=py33-master
  - TOX_ENV=pypy-1.4
  - TOX_ENV=pypy-1.5
  - TOX_ENV=pypy-1.6
  - TOX_ENV=pypy-master
before_install:
  - sudo add-apt-repository ppa:fkrull/deadsnakes -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq python2.6 python2.7 python3.3 pypy
  - export DJANGO_SETTINGS_MODULE=autofixture_tests.settings
  - sudo pip install tox
script:
  - tox -e $TOX_ENV -v
branches:
  only:
    - master

